version: '3.8'
services:
  dev-db:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: fiu-fit-user
      MONGO_INITDB_ROOT_PASSWORD: TAxy57EnI16b38aN
      MONGO_INITDB_DATABASE: workout-service-db
    networks:
      - fiu-fit

  test-db:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - fiu-fit
networks:
  fiu-fit: